### ISSUE TITLE
DBCommand exception

### ISSUE THREAD

**Issue by ustits** [Adven27/Exam#8]
After latest commits getting exception on tests startup related to `DBCommand`:
**build:** current master branch
**configs:** 
``` java
private final ExamExtension appTest = new ExamExtension()
            .rest(APP_URL).end()
            .kafka().brokers(BROKERS_LIST).end();
```
**exception:**
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.adven.concordion.extensions.exam.db.commands.DBCommand.<init>, parameter dbTester

	at com.adven.concordion.extensions.exam.db.commands.DBCommand.<init>(DBCommand.kt)
	at com.adven.concordion.extensions.exam.db.commands.DBShowCommand.<init>(DBShowCommand.java:22)
	at com.adven.concordion.extensions.exam.CommandRegistry.<init>(CommandRegistry.java:43)
	at com.adven.concordion.extensions.exam.ExamExtension.addTo(ExamExtension.java:169)
	at org.concordion.internal.extension.FixtureExtensionLoader.addExtensions(FixtureExtensionLoader.java:21)
	at org.concordion.internal.FixtureRunner.<init>(FixtureRunner.java:17)
	at org.concordion.integration.junit4.ConcordionRunner.<init>(ConcordionRunner.java:62)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by Adven27** [comment]
fixed
